# Generated by Django 4.2.6 on 2023-10-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinference',
            name='image_inf',
            field=models.ImageField(upload_to='inference_img/'),
        ),
    ]
