# Generated by Django 4.2.6 on 2023-11-10 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='videos/')),
                ('media_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('media_second', models.CharField(max_length=60)),
            ],
        ),
    ]
